### PR TITLE
Fixed issue causing crashes with D3D12 setting

### PR DESCRIPTION
**Pull request by qd201211**

### CODE REVIEW

**Comment by SteffenL** [comment]
Thanks for this PR! I cleaned up the code slightly and will do some testing.

I would prefer not to change any of the user's files without asking them but I think we can merge this and then see how to improve it.

**Comment by qd201211** [comment]
> Thanks for this PR! I cleaned up the code slightly and will do some testing.
> 
> I would prefer not to change any of the user's files without asking them but I think we can merge this and then see how to improve it.

Okay, I completely understand your idea. I think we can set up a config file to configure some basic information, allowing users with issues to manually enable this option through the config file.

**Comment by SteffenL** [comment]
After some testing, I can confirm that the game doesn't launch (before this PR) when D3D12 is used.

Copying `ph\work\bin\x64\D3D12Core.dll` into `DevTools\bin` seems to solve the issue without editing any files.

Can you please check?

**Comment by SteffenL** [comment]
I can also confirm that this PR allows the game to run when the user previous was using D3D12 since it changes the setting to D3D11.

**Comment by qd201211** [comment]
> I can also confirm that this PR allows the game to run when the user previous was using D3D12 since it changes the setting to D3D11.

Alright, I'll give it a try.

**Comment by qd201211** [comment]
> After some testing, I can confirm that the game doesn't launch (before this PR) when D3D12 is used.
> 
> Copying `ph\work\bin\x64\D3D12Core.dll` into `DevTools\bin` seems to solve the issue without editing any files.
> 
> Can you please check?

I tried it myself by placing the D3D12Core.dll from the main game into devtools/bin and using DX12 in the video settings, but it didn't work. The logo flashed briefly and then the game crashed, unable to open.Switching back to DX11 allows the game to open.

**Comment by SteffenL** [comment]
The root cause of this startup issue was that some DLLs are present in the main build of the game but not DevTools, and therefore some DLLs could not be loaded. For example, when launching the game while using the D3D12 rendering setting, `D3D12Core.dll` could not be found by the game.

Initial attempts at fixing this by redirecting only `D3D12Core.dll` appeared successful in my environment, but persisted in other environments.

There was also mixed success with DLL redirection seemingly depending on the NVIDIA GPU driver version installed due to the hooked `LoadLibraryW` not being called in some environments, and hooking `LdrLoadDll` sorted that out.

Another example of a DLL that isn't present in DevTools is `NRD.dll` (NVIDIA Real-Time Denoisers).

The latest released code attempts to redirect any DLL that cannot be loaded, and that's what appears to have fixed the issue once and for all.

Thank you, @qd201211, as well as others on Discord, for testing new builds and providing feedback.

I also appreciate that you provided this workaround which has also been confirmed by others to have helped.

Since the D3D12 rendering setting is now usable, this workaround isn't needed anymore, and therefore I won't merge this PR; however, I've fixed the new merge conflicts for you and tidied up the code slightly.

**Pull request closed without merging**
